modLoader = "javafml"
loaderVersion = "[38,)"
license = "Apache-2.0"

[[mods]]
modId = "armorsoundtweak"
version = "${file.jarVersion}"
displayName = "Armor Sound Tweak"
authors = "Chloe Dawn"
description = """Plays the respective equip sound when (un)equipping armor in a menu"""

[[dependencies.armorsoundtweak]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
side = "CLIENT"

[[dependencies.armorsoundtweak]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
side = "CLIENT"

[[dependencies.armorsoundtweak]]
modId = "curios"
mandatory = false
versionRange = "[1.18-5,)"
side = "CLIENT"
