modLoader = "javafml"
loaderVersion = "[28,)"
license = "Apache-2.0"

[[mods]]
modId = "armorsoundtweak"
version = "${file.jarVersion}"
displayName = "Armor Sound Tweak"
authors = "Chloe Dawn"
description = """Plays the respective equip sound when (un)equipping armor in a menu"""

[[dependencies.armorsoundtweak]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,1.17)"
side = "CLIENT"

[[dependencies.armorsoundtweak]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
side = "CLIENT"

[[dependencies.armorsoundtweak]]
modId = "curios"
mandatory = false
versionRange = "[1.16.4-4.0.4.0,)"
side = "CLIENT"
